micronaut:
    application:
        name: complete
    server:
        port: 8080
#tag::awss3[]
aws:
    s3:
        region: ${AWS_S3_REGION}
        bucket: ${AWS_S3_BUCKET}
        multipart-upload-threshold: 5248000
        max-upload-threads: 5
#end::awss3[]
#tag::aws[]
    key: ${AWS_ACCESS_KEY_ID}
    secret: ${AWS_SECRET_KEY}
#end::aws[]